"""update: revise column name in custom terms

Revision ID: 20ee284a3212
Revises: aff5b282f78f
Create Date: 2024-07-09 11:00:18.784317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ee284a3212'
down_revision = 'aff5b282f78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms_custom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_comment', sa.Text(), nullable=True))
        batch_op.drop_column('definition_zh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms_custom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition_zh', sa.TEXT(), nullable=True))
        batch_op.drop_column('column_comment')

    # ### end Alembic commands ###
