"""update: extension_template_simple_multimedia

Revision ID: 23326e06ef78
Revises: e360ca7ce46d
Create Date: 2024-06-18 14:24:24.774164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23326e06ef78'
down_revision = 'e360ca7ce46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_extension_simple_multimedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('column_type', sa.String(), nullable=True),
    sa.Column('definition_zh', sa.Text(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_extension_simple_multimedia')
    # ### end Alembic commands ###
