"""update: add projects

Revision ID: 3cce4b5b85bc
Revises: 7478e9e2f9c0
Create Date: 2024-07-16 09:43:36.536881

"""
from alembic import op
import sqlalchemy as sa
from data_template.model import JsonEncodedDict 


# revision identifiers, used by Alembic.
revision = '3cce4b5b85bc'
down_revision = '7478e9e2f9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('table_content', JsonEncodedDict(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
