"""update: extension_template_extended_resource_relationship

Revision ID: 5e4df7c97b52
Revises: 45ac0efbe9e6
Create Date: 2024-06-18 15:27:05.013025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4df7c97b52'
down_revision = '45ac0efbe9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_extension_resource_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('column_type', sa.String(), nullable=True),
    sa.Column('definition_zh', sa.Text(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_extension_resource_relationship')
    # ### end Alembic commands ###
