"""update: add theme template, ltser

Revision ID: 6f22b860ddee
Revises: 7dce7a273748
Create Date: 2024-07-09 09:44:57.640023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f22b860ddee'
down_revision = '7dce7a273748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_theme_ltser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('column_type', sa.String(), nullable=True),
    sa.Column('definition_zh', sa.Text(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_theme_ltser')
    # ### end Alembic commands ###
