"""update: add custom template

Revision ID: 7478e9e2f9c0
Revises: 20ee284a3212
Create Date: 2024-07-10 10:52:05.069768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7478e9e2f9c0'
down_revision = '20ee284a3212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_title', sa.String(), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_custom')
    # ### end Alembic commands ###
