"""update: add core template, others

Revision ID: 7dce7a273748
Revises: 749cbb46770f
Create Date: 2024-07-08 16:30:30.873355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dce7a273748'
down_revision = '749cbb46770f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_core_others',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('column_type', sa.String(), nullable=True),
    sa.Column('definition_zh', sa.Text(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_core_others')
    # ### end Alembic commands ###
