"""update: error_messages

Revision ID: 96bab67a04a8
Revises: 3cce4b5b85bc
Create Date: 2024-10-01 14:25:10.103990

"""
from alembic import op
import sqlalchemy as sa
from data_template.model import JsonEncodedDict 


# revision identifiers, used by Alembic.
revision = '96bab67a04a8'
down_revision = '3cce4b5b85bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('content', JsonEncodedDict(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error_messages')
    # ### end Alembic commands ###
