"""update: add custom terms

Revision ID: aff5b282f78f
Revises: 6f22b860ddee
Create Date: 2024-07-09 10:58:45.827002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff5b282f78f'
down_revision = '6f22b860ddee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms_custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('column_type', sa.String(), nullable=True),
    sa.Column('definition_zh', sa.Text(), nullable=True),
    sa.Column('last_edited', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terms_custom')
    # ### end Alembic commands ###
