"""update: core_template_occurrence

Revision ID: c2b991516a88
Revises: 
Create Date: 2024-06-18 10:44:45.482951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b991516a88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_core_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('column_type', sa.String(), nullable=True),
    sa.Column('definition_zh', sa.Text(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_core_checklist', schema=None) as batch_op:
        batch_op.drop_column('column_name_zh')
        batch_op.drop_column('definition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_core_checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('column_name_zh', sa.VARCHAR(), nullable=True))

    op.drop_table('template_core_occurrence')
    # ### end Alembic commands ###
