"""update: extension_template_occurrence

Revision ID: e360ca7ce46d
Revises: 06847cce4e19
Create Date: 2024-06-18 14:05:08.503225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e360ca7ce46d'
down_revision = '06847cce4e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_extension_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('column_type', sa.String(), nullable=True),
    sa.Column('definition_zh', sa.Text(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_extension_occurrence')
    # ### end Alembic commands ###
